# Numpy

In [1]:
# Importing necessary libary

In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
# Array creation

In [5]:
a= np.array(10)

In [6]:
type(a)

numpy.ndarray

In [8]:
z=np.array(10)
z.ndim

0

In [9]:
# one dimension array

In [10]:
q=np.array([12,51,68])

In [11]:
q.ndim

1

In [12]:
# two dimensional array

In [13]:
e=np.array([[59,35,48,89]])

In [14]:
e.ndim

2

In [20]:
# 3 Dimensional Array
p=np.array([[[56,35,48,89]]])
p.ndim

3

In [21]:
#change data type of teh array element

In [22]:
a=np.array([15,96,75,28])

In [23]:
a.dtype

dtype('int32')

In [24]:
a=np.array([15,96,75,28],dtype='float')

In [25]:
print(a.dtype)

float64


In [26]:
a

array([15., 96., 75., 28.])

# Other ways of creating array
1. arrange
2. linspace
3. zeros
4. ones
5. ramdom


In [28]:
a=np.arange(1,21,3)
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [29]:
b=np.linspace(1,5,15, retstep=True)
b

(array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
        2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
        3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ]),
 0.2857142857142857)

In [30]:
z=np.zeros([2,2])
z

array([[0., 0.],
       [0., 0.]])

In [31]:
o=np.ones([5,5])
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
r=np.random.rand(5,5)
r

array([[0.95869988, 0.88020083, 0.87774854, 0.59433268, 0.72965708],
       [0.23810777, 0.08559786, 0.48578632, 0.60303934, 0.64410155],
       [0.60938521, 0.18012238, 0.48903702, 0.94622836, 0.47490646],
       [0.00432522, 0.98604355, 0.4034992 , 0.07532092, 0.93427232],
       [0.54631694, 0.54337092, 0.63270133, 0.73781531, 0.69669115]])

In [35]:
r=np.random.randint(5,size=10)
r

array([3, 2, 1, 4, 0, 0, 1, 1, 2, 1])

# Slicing and indexing of arrays

In [36]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
a[0,0]

1

In [38]:
a[1,2]

6

In [39]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
a[0,1:]

array([2, 3])

In [41]:
a[0:,1:]

array([[2, 3],
       [5, 6]])

In [42]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
# exicute 1 & 6

In [44]:
a[[0,1],[0,2]]

array([1, 6])

In [45]:
# 3&4

In [50]:
a[[0,1],[2,0]]

array([3, 4])

# Reshaping the arrays

In [51]:
a=np.random.rand(5,2)
a

array([[0.82818038, 0.93056573],
       [0.03445693, 0.14499911],
       [0.58888189, 0.99114504],
       [0.29082506, 0.91697237],
       [0.02354155, 0.01751962]])

In [52]:
a.reshape(2,5)

array([[0.82818038, 0.93056573, 0.03445693, 0.14499911, 0.58888189],
       [0.99114504, 0.29082506, 0.91697237, 0.02354155, 0.01751962]])

In [54]:
a.reshape(1,10)

array([[0.82818038, 0.93056573, 0.03445693, 0.14499911, 0.58888189,
        0.99114504, 0.29082506, 0.91697237, 0.02354155, 0.01751962]])

In [55]:
a.reshape(5,2)

array([[0.82818038, 0.93056573],
       [0.03445693, 0.14499911],
       [0.58888189, 0.99114504],
       [0.29082506, 0.91697237],
       [0.02354155, 0.01751962]])

In [56]:
a.reshape(10,1)

array([[0.82818038],
       [0.93056573],
       [0.03445693],
       [0.14499911],
       [0.58888189],
       [0.99114504],
       [0.29082506],
       [0.91697237],
       [0.02354155],
       [0.01751962]])

In [58]:
a.reshape(-1,5)

array([[0.82818038, 0.93056573, 0.03445693, 0.14499911, 0.58888189],
       [0.99114504, 0.29082506, 0.91697237, 0.02354155, 0.01751962]])

In [57]:
a.reshape(5,-1)

array([[0.82818038, 0.93056573],
       [0.03445693, 0.14499911],
       [0.58888189, 0.99114504],
       [0.29082506, 0.91697237],
       [0.02354155, 0.01751962]])

# Aggregate Functions

In [59]:
a.min()

0.017519621603516056

In [60]:
a.std()

0.394583819028737

In [61]:
a.var()

0.15569639023930307

# Stacking

In [62]:
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8])

In [63]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 4, 5, 6, 7, 8])

In [64]:
np.vstack([a,b])

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])